<?php
return [
  'settings' => [
    'site_name' => '微信小程序',
    'slogan' => '专爱微信小程序开发',
    'description' => '微信小程序开发交流，资源分享',
    'icp' => '',
    'admin_email' => '',
    'offline' => 0,
    'offline_msg' => '网站维护中，请稍后访问',
    'access_auth' => 0,
    'email_verify' => 0,
    'admin_verify' => 0,
    'close_register' => 0,
    'username_filter' => '',
    'captcha_enabled' => 0,
    'autolink' => 0,
    'autolink_filter' => [
    ],
    'theme' => '',
    'theme_mobile' => '',
    'head_meta' => '',
    'analytics_code' => '<script>var _hmt = _hmt || [];(function() {  var hm = document.createElement("script");  hm.src = "//hm.baidu.com/hm.js?5a87cd7ab7baa74f3c8128528ebc4f9c";  var s = document.getElementsByTagName("script")[0];   s.parentNode.insertBefore(hm, s);})();</script>',
    'footer_links' => [
    ],
    'timezone' => 'Asia/Shanghai',
    'editor' => 'wysibb',
    'cache_enabled' => 0,
    'cache_time' => 10,
    'auth_enabled' => 0,
    'qq_appid' => '',
    'qq_appkey' => '',
    'qq_scope' => 'get_user_info',
    'wb_key' => '',
    'wb_secret' => '',
    'index_pagesize' => 20,
    'list_pagesize' => 20,
    'comment_pagesize' => 20,
    'hot_topic_num' => 10,
    'hot_node_num' => 20,
    'edit_space' => 30,
    'topic_space' => 30,
    'comment_space' => 20,
    'alias_static' => '',
    'alias_avatar' => '',
    'alias_upload' => '',
    'mailer_host' => '',
    'mailer_port' => 0,
    'mailer_encryption' => '',
    'mailer_username' => '',
    'mailer_password' => '',
    'upload_avatar' => 'local',
    'upload_file' => 'disable',
    'upload_file_regday' => 30,
    'upload_file_topicnum' => 20,
    'upload_remote' => '',
    'upload_remote_info' => '',
    'upload_remote_url' => '',
  ]
];
